# Generated by Django 3.0.8 on 2022-05-15 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', related_query_name='imagenes', to='servicios.Product')),
            ],
        ),
    ]
