"""
Django settings for sabia project.

Generated by 'django-admin startproject' using Django 3.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'j@i7ac0khclyp(n)^um)d(jr^5jxj(l0=5^+4i(t6o@f)u)_pq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app.home',
    'app.usuario',
    'app.denuncias',
    'app.adopciones',
    'app.donaciones',
    'app.blogs',
    'pwa',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sabia.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sabia.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': 'SabiaFinalDB',
            'USER': 'postgres',
            'PASSWORD': 'cristian',
            'HOST': 'localhost',
            'PORT': 5432,

    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    # 
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'es-EC'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

LANGUAGES=[
    ('en' ,'Ingles'),
    ('es' ,'Español')

]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'


MEDIA_ROOT = os.path.join(BASE_DIR,'media')


STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'
STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'),)

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# <----------- Redireccion Login & LogOut ------------->

LOGIN_REDIRECT_URL = 'pagina'
LOGOUT_REDIRECT_URL = '/'

# <----------- PWA - CONFIGURACION ------------->
PWA_APP_NAME = 'SABIA' 
PWA_APP_DESCRIPTION = "sbaia_portal" 
PWA_APP_THEME_COLOR = '#0A0302'
PWA_APP_BACKGROUND_COLOR = '#43914E'
PWA_APP_DISPLAY = 'standalone'
PWA_APP_SCOPE = '.' 
PWA_APP_ORIENTATION = 'any' 
PWA_APP_START_URL = '/' 

PWA_APP_STATUS_BAR_COLOR = 'default' 
PWA_APP_ICONS = [ 
 {
    'src': '/static/pwa72_72.png', 
    "sizes": "72x72",
    "type": "image/png"
  }, 
  {
   'src': '/static/pwa96_96.png', 
    "sizes": "96x96",
    "type": "image/png"
  }, 
  {
   'src': '/static/pwa144_144.png', 
    "sizes": "144x144",
    "type": "image/png"
  }, 
    { 
        'src': '/static/pwa3.png', 
        'sizes': '160x160',
        'type': "image/png",
        
        }, 
  {
      'src': '/static/pwa192_192.png', 
    "sizes": "192x192",
    "type": "image/png"
  }]
PWA_APP_ICONS_APPLE =  [ 


 {
     'src': '/static/pwa72_72.png', 
    "sizes": "72x72",
    "type": "image/png"
  }, 
  {
   'src': '/static/pwa96_96.png', 
    "sizes": "96x96",
    "type": "image/png"
  }, 
  {
   'src': '/static/pwa144_144.png', 
    "sizes": "144x144",
    "type": "image/png"
  }, 
    { 
        'src': '/static/pwa3.png', 
        'sizes': '160x160',
        'type': "image/png",
        
        }, 
  {
      'src': '/static/pwa192_192.png', 
    "sizes": "192x192",
    "type": "image/png"
  }]


PWA_APP_SPLASH_SCREEN = [ { 'src': '/static/img/huella.png', 'media': '(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2)' } ]
PWA_APP_DIR = 'ltr' 
PWA_APP_LANG = 'en-US'

PWA_SERVICE_WORKER_PATH = os.path.join(BASE_DIR, "serviceworker.js")

#PWA_APP_DEBUG_MODE = False
